
services:
  database:
    image: "postgres:16.0-alpine3.18"
    container_name: postgres-security
    environment:
      POSTGRES_DB: security_db
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - "4321:5432"
volumes:
  postgres: