spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/security_db
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-plataform: org.hibernate.dialect.PostgreSQLDialect